services:
  oriona-agents:
    image: ${DOCKER_REPOSITORY}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: oriona-agents
    env_file:
      - ${SERVER_PROJECT_PATH}.env
    ports:
      - "${SERVER_PROJECT_PUBLIC_PORT}:8000"
    restart: unless-stopped